using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.WPF.Reflection.Attributes;

namespace JourneymanVendorPatcher
{
    public class Settings
    {
        [SettingName("# of travel packs to distribute")]
        [Tooltip("Must be a positive integer")]
        public int Count = 3;
    }

    public class Program
    {
        private static Lazy<Settings> _settings = null!;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings("settings", "settings.json", out _settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "JourneymanVendorPatcher.esp")
                .Run(args);
        }

        private static readonly ModKey Journeyman = ModKey.FromNameAndExtension("Journeyman.esp");

        private static readonly HashSet<string> Edids = new()
        {
            "DLC2RRGeldisVendorChest",
            "MerchantCaravanAChest",
            "MerchantCaravanBChest",
            "MerchantCaravanCChest",
            "MerchantDawnstarWindpeakInnChest",
            "MerchantDragonBridgeFourShieldsTavernChest",
            "MerchantFalkreathDeadMansDrinkChest",
            "MerchantIvarsteadVilemyrInnChest",
            "MerchantKynesgroveBraidwoodInnChest",
            "MerchantMarkarthSilverFishInnChest",
            "MerchantMorthalMoorsideInnChest",
            "MerchantNightgateInnChest",
            "MerchantOldHroldanHangedManInnChest",
            "MerchantRiftenBeeandBarbChest",
            "MerchantRiverwoodSleepingGiantChest",
            "MerchantRiverwoodTraderChest",
            "MerchantRoriksteadFrostFruitInnChest",
            "MerchantSolitudeWinkingSkeeverChest",
            "MerchantWhiterunBannerdMareChest",
            "MerchantWhiterunBelethorsGoodsChest",
            "MerchantWhiterunDrunkenHuntsmanChest",
            "MerchantWindhelmCandlehearthHallChest",
            "MerchantWinterholdFrozenHearthChest",
        };

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            if (!state.LoadOrder.ContainsKey(Journeyman))
                throw new Exception("ERROR: Journeyman.esp not found in load order");

            var travelPack = state.LinkCache.Resolve<IMiscItemGetter>("MAG_TravelPack");
            var travelPackKywd = state.LinkCache.Resolve<IKeywordGetter>("MAG_TravelPackKeyword");

            var innkeeperFormlist = state.LinkCache.Resolve<IFormListGetter>("VendorItemsInnkeeper");
            var patchedFormlist = state.PatchMod.FormLists.GetOrAddAsOverride(innkeeperFormlist);
            patchedFormlist.Items.Add(travelPackKywd);

            foreach (var merchantChest in state.LoadOrder.PriorityOrder.Container().WinningContextOverrides())
            {
                if (!Edids.Contains(merchantChest.Record.EditorID!)) continue;

                var patchedChest = state.PatchMod.Containers.GetOrAddAsOverride(merchantChest.Record);

                patchedChest.Items!.Add(new ContainerEntry
                {
                    Item = new ContainerItem
                    {
                        Item = travelPack.ToLink(),
                        Count = _settings.Value.Count
                    }
                });

                Console.WriteLine($"Added {_settings.Value.Count} travel packs to {merchantChest.Record.EditorID}");
            }

            state.PatchMod.ModHeader.Flags = SkyrimModHeader.HeaderFlag.LightMaster;
        }
    }
}
